CREATE DATABASE IF NOT EXISTS chatbot 
  CHARACTER SET UTF8 
  COLLATE UTF8_CZECH_CI;

USE chatbot;

CREATE TABLE IF NOT EXISTS subjects (
  subjectId INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) UNIQUE NOT NULL,
  abbreviation VARCHAR(3) UNIQUE NOT NULL,
  description LONGTEXT
);

CREATE TABLE IF NOT EXISTS users (
  userId INT PRIMARY KEY AUTO_INCREMENT,
  firstName VARCHAR(50),
  lastName VARCHAR(50),
  email VARCHAR(100) UNIQUE NOT NULL,
  passwordHash VARCHAR(255) NOT NULL,
  role ENUM('Administrátor', 'Učitel') NOT NULL
);

CREATE TABLE IF NOT EXISTS topics (
  topicId INT PRIMARY KEY AUTO_INCREMENT,
  subjectId INT NOT NULL,
  userId INT,
  name VARCHAR(100) UNIQUE NOT NULL,
  description LONGTEXT,
  isPrivate BOOLEAN DEFAULT FALSE,
  CONSTRAINT FK_TOPICS_SUBJECTS FOREIGN KEY (subjectId)
      REFERENCES subjects (subjectId)
      ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_TOPICS_USERS FOREIGN KEY (userId)
      REFERENCES users (userId)
      ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS prompts (
  promptId INT PRIMARY KEY AUTO_INCREMENT,
  message LONGTEXT,
  attachedFile LONGBLOB
);

CREATE TABLE IF NOT EXISTS topics_prompts (
  topicId INT NOT NULL,
  promptId INT NOT NULL,
  PRIMARY KEY (topicId, promptId),
  CONSTRAINT FK_TOPICS_PROMPTS_TOPICS FOREIGN KEY (topicId)
      REFERENCES topics (topicId)
      ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_TOPICS_PROMPTS_PROMPTS FOREIGN KEY (promptId)
      REFERENCES prompts (promptId)
      ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS questions (
  questionId INT PRIMARY KEY AUTO_INCREMENT,
  text LONGTEXT NOT NULL,
  type ENUM('Ano / Ne', 'Výběr z odpovědí', 'Otevřená otázka') NOT NULL,
  difficulty ENUM('Lehká', 'Těžká', 'Střední') NOT NULL,
  points INT NOT NULL
);

CREATE TABLE IF NOT EXISTS users_subjects (
  userId INT NOT NULL,
  subjectId INT NOT NULL,
  PRIMARY KEY (userId, subjectId),
  CONSTRAINT FK_USERS_SUBJECTS_USERS FOREIGN KEY (userId)
      REFERENCES users (userId)
      ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_USERS_SUBJECTS_SUBJECTS FOREIGN KEY (subjectId)
      REFERENCES subjects (subjectId)
      ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS tests (
  testId INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  difficulty ENUM('Lehká', 'Těžká', 'Střední') NOT NULL,
  numberOfQuestions INT NOT NULL,
  timeLimit INT NOT NULL,
  promptId INT UNIQUE NOT NULL,
  userId INT NOT NULL,
  CONSTRAINT FK_TESTS_PROMPTS FOREIGN KEY (promptId)
      REFERENCES prompts (promptId)
      ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_TESTS_USERS FOREIGN KEY (userId)
      REFERENCES users (userId)
      ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS questions_tests (
  questionId INT NOT NULL,
  testId INT NOT NULL,
  PRIMARY KEY (questionId, testId),
  CONSTRAINT FK_QUESTIONS_TESTS_QUESTIONS FOREIGN KEY (questionId)
      REFERENCES questions (questionId)
      ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_QUESTIONS_TESTS_TESTS FOREIGN KEY (testId)
      REFERENCES tests (testId)
      ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS answers (
  answerId INT PRIMARY KEY AUTO_INCREMENT,
  text LONGTEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS questions_answers (
  questionId INT NOT NULL,
  answerId INT NOT NULL,
  isCorrect BOOLEAN NOT NULL,
  explanation LONGTEXT,
  PRIMARY KEY (questionId, answerId),
  CONSTRAINT FK_QUESTIONS_ANSWERS_QUESTIONS FOREIGN KEY (questionId)
      REFERENCES questions (questionId)
      ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_QUESTIONS_ANSWERS_ANSWERS FOREIGN KEY (answerId)
      REFERENCES answers (answerId)
      ON DELETE CASCADE ON UPDATE CASCADE
);